overrides:
  '@earendil-works/pi-agent-core': 1.0.2
  '@earendil-works/pi-ai': 1.0.2
  '@earendil-works/pi-tui': 1.0.2
  '@earendil-works/pi-coding-agent': 1.0.2

allowBuilds:
  '@google/genai': false
  esbuild: true
  lefthook: false
  protobufjs: false
